reads:
  desiree:
    name: desiree
    fastq: KFRAG_00469.fastq.gz # Desiree
    genome_size: 844 # megabases
    coverage: 65
  ivp48:
    name: ivp48
    fastq: KFRAG_00470.fastq.gz # IVP-48
    genome_size: 844 # megabases
    coverage: 35

mer_size:
  - 30

error_rate: 0.01
