name: merluvlee
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - graphviz=2.40.1
  - jellyfish=2.2.10
  - r-base=3.6.0
  - r-dplyr=0.8.3
  - r-ggplot2=3.2.0
  - snakemake=5.4.5
  - sra-tools=2.9.6
  - unzip=6.0
  - wget=1.20.1
